version: '3'
services:
  chatfe:
    container_name: chatfe
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./src:/app/src
    env_file: ./.env
    ports:
      - '5173:5173'
    networks:
      - livechat

networks: 
    livechat:
        driver: bridge